command_timeout = 1500
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$python\
$sudo\
$line_break\
$time\
$os\
$shell
"""

[cmd_duration]
disabled = true

[directory]
truncation_length = 100
truncate_to_repo = false
style = "bold #719bff"

[hostname]
style = "bold #ff5a00"

[git_branch]
style = "bold #fd9bac"

[python]
python_binary = "python3"
symbol = ''

[time]
disabled = false
format = '[\[$time\]](#cddfff) '
time_format = "%T"
utc_time_offset = "+9"

[username]
style_user = "bold #ffb9c7"
style_root = "bold #ff4100"

