[directory]
truncation_length = 100
truncate_to_repo = false
style = "bold #719bff"

[git_branch]
style = "bold #fd9bac"

[time]
disabled = false
format = '[\[$time\]](#cddfff) '
time_format = "%T"
utc_time_offset = "+9"

[cmd_duration]
disabled = true

[vagrant]
disabled = true

[perl]
disabled = true

[python]
python_binary = "python3"
